"""add_violation_details_to_student_quizzes

Revision ID: 0b4d50f89aba
Revises: b1d062dc8d60
Create Date: 2026-06-11 09:52:20.924398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b4d50f89aba'
down_revision: Union[str, None] = 'b1d062dc8d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_quizzes', sa.Column('violation_details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_quizzes', 'violation_details')
    # ### end Alembic commands ###
