"""add exam_ratio to sessions

Revision ID: 853a8dec0aa2
Revises: b497a65e44f4
Create Date: 2026-05-06 15:52:07.766086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853a8dec0aa2'
down_revision: Union[str, None] = 'b497a65e44f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('exam_ratio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'exam_ratio')
    # ### end Alembic commands ###
