"""add_violation_count_to_student_quizzes

Revision ID: b1d062dc8d60
Revises: b1f4fe4ddb8c
Create Date: 2026-06-11 09:09:56.465774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d062dc8d60'
down_revision: Union[str, None] = 'b1f4fe4ddb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_quizzes', sa.Column('violation_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_quizzes', 'violation_count')
    # ### end Alembic commands ###
