"""add activated_at to sessions

Revision ID: b1f4fe4ddb8c
Revises: 853a8dec0aa2
Create Date: 2026-05-06 16:51:11.536597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f4fe4ddb8c'
down_revision: Union[str, None] = '853a8dec0aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'activated_at')
    # ### end Alembic commands ###
